/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package front.panels;

import controler.ClientControler;
import domain.Zaposleni;
import front.tableModels.ZaposleniTableModel;
import javax.swing.JOptionPane;

/**
 *
 * @author jevrozim
 */
public class DeleteZaposleniPanel extends javax.swing.JPanel {

    private PanelFrame frame;
    private ZaposleniTableModel model;

    /**
     * Creates new form DeleteZaposleniPanel
     */
    public DeleteZaposleniPanel() {
        model = new ZaposleniTableModel();
        initComponents();
        table.setModel(model);
    }

    public void setFrame(PanelFrame p) {
        frame = p;
        frame.setTitle("Brisanje zaposlenog");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        deletebtn = new javax.swing.JButton();

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table);

        deletebtn.setText("Ukloni");
        deletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(deletebtn)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(deletebtn)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void deletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebtnActionPerformed
        // TODO add your handling code here:
//        int row=table.getSelectedRow();
//        Zaposleni pokojni=model.getZaposleni(row);
//        
//        int odgovor=JOptionPane.showConfirmDialog(frame, "Da li ste sigurni da zelite da uklonite "+pokojni,"", JOptionPane.YES_NO_OPTION);
//        
//        if(odgovor==JOptionPane.YES_OPTION){
//        ClientControler.getInstance().deleteZaposleni(pokojni);
//        //VIDI STA VRATI KLIJENT KONTROLER JER MOZDA NEUSPESNO UKLONI ZAPOSLENOG
//        model=new ZaposleniTableModel();
//        table.setModel(model);
//        frame.getMessagetxt().setText("Uspesno uklonjen "+pokojni);
//        }
        int row=table.getSelectedRow();
        Zaposleni pokojni=model.getZaposleni(row);
        int odgovor=JOptionPane.showConfirmDialog(frame, "Da li ste sigurni da zelite da uklonite "+pokojni,"", JOptionPane.YES_NO_OPTION);
        
        if(odgovor==JOptionPane.YES_OPTION){
            try{
                ClientControler.getInstance().deleteZaposleni(pokojni);
                model=new ZaposleniTableModel();
                table.setModel(model);
                frame.getMessagetxt().setText("Uspesno uklonjen "+pokojni);
            }catch(Exception e){
                frame.getMessagetxt().setText(e.getMessage());
            }
        }
    }//GEN-LAST:event_deletebtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deletebtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
