package front.panels;

import controler.ClientControler;
import domain.Zaposleni;
import front.MainFrame;
import java.awt.Window;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
/**
 *
 * @author jevrozim
 */
public class NoviZaposleniPanel extends javax.swing.JPanel {

    private PanelFrame frame;

    /**
     * Creates new form NoviZaposleniPanel
     */
    public NoviZaposleniPanel() {
        initComponents();

    }

    public void setFrame(PanelFrame frame) {
        this.frame = frame;
        frame.setTitle("Dodavanje novog zaposlenog");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField3 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        continuebtn = new javax.swing.JButton();
        ussernametxt = new javax.swing.JTextField();
        imetxt = new javax.swing.JTextField();
        prezimetxt = new javax.swing.JTextField();
        passwordtxt = new javax.swing.JTextField();

        jTextField3.setText("jTextField1");

        jLabel1.setText("Ime");

        jLabel2.setText("Prezime");

        jLabel3.setText("Korisnicko Ime");

        jLabel4.setText("Sifra");

        continuebtn.setText("Kreiraj zaposlenog");
        continuebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continuebtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(imetxt))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(ussernametxt, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(prezimetxt))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(passwordtxt))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 247, Short.MAX_VALUE)
                        .addComponent(continuebtn)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(imetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(prezimetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(ussernametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(passwordtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(continuebtn)
                .addGap(25, 25, 25))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void continuebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continuebtnActionPerformed
        // TODO add your handling code here:
        if (imetxt.getText().equals("") || prezimetxt.getText().equals("") || ussernametxt.getText().equals("") || passwordtxt.getText().equals("")) {
            System.out.println("Nepravilno uneti podaci za ubacivanje novog zaposlenog");
        } else {
            Zaposleni zaposleni = new Zaposleni(imetxt.getText(), prezimetxt.getText(), ussernametxt.getText(), passwordtxt.getText());
            try {
                zaposleni = ClientControler.getInstance().newZaposleni(zaposleni);
                System.out.println("NAPRAVLJEN JE NOVI ZAPOSLENI " + zaposleni);
                frame.getMessagetxt().setText("Dodat je novi zaposleni " + zaposleni);
                imetxt.setEditable(false);
                prezimetxt.setEditable(false);
                ussernametxt.setEditable(false);
                passwordtxt.setEditable(false);
                continuebtn.setEnabled(false);
                frame.getcacnelbtn().setText("Izadji");
            } catch (Exception e) {
                frame.getMessagetxt().setText(e.getMessage());

            }
        }
    }//GEN-LAST:event_continuebtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton continuebtn;
    private javax.swing.JTextField imetxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField passwordtxt;
    private javax.swing.JTextField prezimetxt;
    private javax.swing.JTextField ussernametxt;
    // End of variables declaration//GEN-END:variables
}
