/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package front.panels;

import controler.ClientControler;
import domain.Zaposleni;
import front.tableModels.ZaposleniTableModel;
import javax.swing.JOptionPane;

/**
 *
 * @author jevrozim
 */
public class ZaposleniPanel extends javax.swing.JPanel {

    private PanelFrame frame;
    private ZaposleniTableModel model;
    private String poruka = "privremeno resenje za slanje poruke za gresku";//nisam siguran cemu ovo trenutni rosic je zaboravio sta je prosli rosic hteo da uradi

    /**
     * Creates new form DeleteZaposleniPanel
     */
    public ZaposleniPanel() {
        try {
            model = new ZaposleniTableModel();
            initComponents();
            table.setModel(model);
        } catch (Exception e) {
            poruka = e.getMessage();
        }
    }

    public void setFrame(PanelFrame p) {
        frame = p;
        frame.setTitle("Zaposleni akcije");
        frame.getMessagetxt().setText(poruka);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        obrisibtn = new javax.swing.JButton();
        izmenibtn = new javax.swing.JButton();
        kreirajtbn = new javax.swing.JButton();

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table);

        obrisibtn.setText("Ukloni");
        obrisibtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                obrisibtnActionPerformed(evt);
            }
        });

        izmenibtn.setText("Izmeni");
        izmenibtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                izmenibtnActionPerformed(evt);
            }
        });

        kreirajtbn.setText("Kreiraj");
        kreirajtbn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kreirajtbnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(obrisibtn, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(izmenibtn, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(kreirajtbn, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(obrisibtn)
                        .addGap(18, 18, 18)
                        .addComponent(izmenibtn)
                        .addGap(18, 18, 18)
                        .addComponent(kreirajtbn)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void obrisibtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_obrisibtnActionPerformed
        // TODO add your handling code here:
//        int row=table.getSelectedRow();
//        Zaposleni pokojni=model.getZaposleni(row);
//        
//        int odgovor=JOptionPane.showConfirmDialog(frame, "Da li ste sigurni da zelite da uklonite "+pokojni,"", JOptionPane.YES_NO_OPTION);
//        
//        if(odgovor==JOptionPane.YES_OPTION){
//        ClientControler.getInstance().deleteZaposleni(pokojni);
//        //VIDI STA VRATI KLIJENT KONTROLER JER MOZDA NEUSPESNO UKLONI ZAPOSLENOG
//        model=new ZaposleniTableModel();
//        table.setModel(model);
//        frame.getMessagetxt().setText("Uspesno uklonjen "+pokojni);
//        }
        int row = table.getSelectedRow();
        if(row==-1){
            frame.getMessagetxt().setText("Nije oznacen ni jedan zaposleni za ukloniti");
            return;
        }
        Zaposleni pokojni = model.getZaposleni(row);
        int odgovor = JOptionPane.showConfirmDialog(frame, "Da li ste sigurni da zelite da uklonite " + pokojni, "", JOptionPane.YES_NO_OPTION);

        if (odgovor == JOptionPane.YES_OPTION) {
            try {
                ClientControler.getInstance().deleteZaposleni(pokojni);
                model = new ZaposleniTableModel();
                table.setModel(model);
                frame.getMessagetxt().setText("Uspesno uklonjen " + pokojni);
            } catch (Exception e) {
                frame.getMessagetxt().setText(e.getMessage());
            }
        }
    }//GEN-LAST:event_obrisibtnActionPerformed

    private void izmenibtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_izmenibtnActionPerformed
        // TODO add your handling code here:
        //izmeni stvari
        int row = table.getSelectedRow();
        if(row==-1){
            frame.getMessagetxt().setText("Nije odabran ni jedan zaposleni za izmeniti");
            return;
        }
        Zaposleni izmenjeni = model.getZaposleni(row);
        //nesto nesto prikazi novi prozor koji menja zaposlenog
        UpdateZaposleniPanel uf = new UpdateZaposleniPanel(izmenjeni);
        frame.dispose();//privremeno resenje moguce je samo na this frame da zakacim i rifresujem panel
    }//GEN-LAST:event_izmenibtnActionPerformed

    private void kreirajtbnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kreirajtbnActionPerformed
        // TODO add your handling code here:
        //privremeno resenje za novog zaposlenog
        NoviZaposleniPanel p=new NoviZaposleniPanel();
        PanelFrame frame = new PanelFrame(p);
        p.setFrame(frame);
        this.frame.dispose();//privremeno resenje takodje je moguce da samo na this frame zakacim

    }//GEN-LAST:event_kreirajtbnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton izmenibtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton kreirajtbn;
    private javax.swing.JButton obrisibtn;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
