/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package front.panels.stoPaneli;

import controler.ClientControler;
import domain.Sto;
import front.panels.PanelFrame;
import front.tableModels.StoTableModel;
import javax.swing.JOptionPane;

/**
 *
 * @author jevrozim
 */
public class StoPanel extends javax.swing.JPanel {

        private PanelFrame frame;
    private StoTableModel model;
    public StoPanel() {
        
    }
    public void setFrame(PanelFrame frame){
        this.frame=frame;
        try{
           model = new StoTableModel();
            initComponents();
            table.setModel(model);
        } catch (Exception e) {
            frame.getMessagetxt().setText(e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kreirajtbn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        obrisibtn = new javax.swing.JButton();
        izmenibtn = new javax.swing.JButton();

        kreirajtbn.setText("Kreiraj");
        kreirajtbn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kreirajtbnActionPerformed(evt);
            }
        });

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table);

        obrisibtn.setText("Ukloni");
        obrisibtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                obrisibtnActionPerformed(evt);
            }
        });

        izmenibtn.setText("Izmeni");
        izmenibtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                izmenibtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(obrisibtn, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(izmenibtn, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(kreirajtbn, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(97, 97, 97))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(obrisibtn)
                        .addGap(18, 18, 18)
                        .addComponent(izmenibtn)
                        .addGap(18, 18, 18)
                        .addComponent(kreirajtbn)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void kreirajtbnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kreirajtbnActionPerformed
        // TODO add your handling code here:
        //privremeno resenje za novog zaposlenog
        NoviStoPanel p=new NoviStoPanel();
        PanelFrame frame = new PanelFrame(p);
        p.setFrame(frame);
        this.frame.dispose();//privremeno resenje takodje je moguce da samo na this frame zakacim
    }//GEN-LAST:event_kreirajtbnActionPerformed

    private void obrisibtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_obrisibtnActionPerformed
        // TODO add your handling code here:
        int row = table.getSelectedRow();
        if(row==-1){
            frame.getMessagetxt().setText("Nije oznacen ni jedan tip stola za ukloniti");
            return;
        }
        Sto pokojni = model.getSto(row);
        int odgovor = JOptionPane.showConfirmDialog(frame, "Da li ste sigurni da zelite da uklonite " + pokojni, "", JOptionPane.YES_NO_OPTION);

        if (odgovor == JOptionPane.YES_OPTION) {
            try {
                Sto ts=ClientControler.getInstance().deleteSto(pokojni);
                model = new StoTableModel();
                table.setModel(model);
                frame.getMessagetxt().setText("Uspesno uklonjen " + pokojni);
            } catch (Exception e) {
                frame.getMessagetxt().setText(e.getMessage());
            }
        }
    }//GEN-LAST:event_obrisibtnActionPerformed

    private void izmenibtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_izmenibtnActionPerformed
        // TODO add your handling code here:
        //izmeni stvari
        int row = table.getSelectedRow();
        if(row==-1){
            frame.getMessagetxt().setText("Nije odabran ni jedan zaposleni za izmeniti");
            return;
        }
        Sto izmenjeni = model.getSto(row);
        //nesto nesto prikazi novi prozor koji menja zaposlenog
        UpdateStoPanel uf = new UpdateStoPanel(izmenjeni);
        PanelFrame noviFrame=new PanelFrame(uf);
        uf.setFrame(noviFrame);
        frame.dispose();//privremeno resenje moguce je samo na this frame da zakacim i rifresujem panel
    }//GEN-LAST:event_izmenibtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton izmenibtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton kreirajtbn;
    private javax.swing.JButton obrisibtn;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
