/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package front.panels.racunPaleni;

import controler.ClientControler;
import domain.Racun;
import domain.Roba;
import domain.StavkaRacuna;
import front.panels.PanelFrame;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author jevrozim
 */
public class NoviStavkaPanel extends javax.swing.JPanel {

    private PanelFrame frame;
    private Racun racun;
    private ArrayList<Roba> robe;


    public NoviStavkaPanel(Racun racun) {
        initComponents();
        this.racun = racun;
        try {
            robe = ClientControler.getInstance().getAllRoba();
            DefaultComboBoxModel<Roba> model = new DefaultComboBoxModel<>();
            for (Roba r : robe) {
                model.addElement(r);
            }
            jComboBox1.setModel(model);
            this.setVisible(true);
        } catch (Exception e) {
            frame.getMessagetxt().setText(e.getMessage());
            //sve dugmice i forme obustavi
            jComboBox1.setEnabled(false);
            jTextField1.setEditable(false);
            jButton1.setEnabled(false);

        }
    }

    public void setFrame(PanelFrame frame) {
        this.frame = frame;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        jLabel1.setText("kolicina");

        jLabel2.setText("Roba");

        jButton1.setText("kreiraj");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(jButton1)
                        .addGap(0, 144, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1)))
                .addContainerGap(145, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (jComboBox1.getSelectedIndex() == -1) {
            frame.getMessagetxt().setText("Mora se odabrati nesto");
            return;
        }
        if (!(jTextField1.getText().matches("\\d+")) || jTextField1.getText().equals("")) {
            frame.getMessagetxt().setText("neispravno uneta kolicina");
            return;
        }
        int kolicina = Integer.parseInt(jTextField1.getText());
        Roba roba = (Roba) jComboBox1.getSelectedItem();
        System.out.println(racun.getStavkeRacuna().size()+"MNOGO GAFOAFDSADJSADDJSAJDSAIDJSADJDJPAISJDSA");
        racun.getStavkeRacuna().add(new StavkaRacuna(racun, racun.getStavkeRacuna().size() + 1, kolicina * roba.getCena(), kolicina, roba));
        System.out.println(racun.getStavkeRacuna().size());
        try {
            Racun info = ClientControler.getInstance().updateRacun(racun);
            frame.getMessagetxt().setText("Uspesno uneta stavka racuna, id racuna" + info.getIdRacun());
            System.out.println(info.getStavkeRacuna().size());
            jComboBox1.setEnabled(false);
            jTextField1.setEditable(false);
            jButton1.setEnabled(false);
        } catch (Exception e) {
            frame.getMessagetxt().setText(e.getMessage());
            jComboBox1.setEnabled(false);
            jTextField1.setEditable(false);
            jButton1.setEnabled(false);

        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<Roba> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
