/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package front.panels.racunPaleni;

import controler.ClientControler;
import domain.Racun;
import domain.Roba;
import domain.StavkaRacuna;
import domain.Sto;
import front.panels.PanelFrame;
import front.tableModels.RacunTableModel;
import front.tableModels.StavkaRacunaTableModel;
import java.time.LocalTime;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author jevrozim
 */
public class RacunPanel extends javax.swing.JPanel {

    private PanelFrame frame;
    private RacunTableModel modelRacun;
    private StavkaRacunaTableModel modelStavka;

    public void setFrame(PanelFrame frame) {
        this.frame = frame;
        try {
            modelRacun = new RacunTableModel();
            racuntab.setModel(modelRacun);
            ArrayList<Sto> stolovi;
            stolovi = ClientControler.getInstance().getAllSto();
            DefaultComboBoxModel<Sto> model = new DefaultComboBoxModel<>();
            for (Sto r : stolovi) {
                model.addElement(r);
            }
            jComboBox1.setModel(model);
            this.setVisible(true);
        } catch (Exception ex) {
            frame.getMessagetxt().setText(ex.getMessage());
            dodajStavkubtn.setEnabled(false);
            obrisiRacunbtn.setEnabled(false);
            prikaziStavkebtn.setEnabled(false);

        }
    }

    /**
     * Creates new form RacunPanel
     */
    public RacunPanel() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        racuntab = new javax.swing.JTable();
        prikaziStavkebtn = new javax.swing.JButton();
        dodajStavkubtn = new javax.swing.JButton();
        obrisiRacunbtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        racuntab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(racuntab);

        prikaziStavkebtn.setText("prikazi stavke");
        prikaziStavkebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prikaziStavkebtnActionPerformed(evt);
            }
        });

        dodajStavkubtn.setText("dodaj stavku");
        dodajStavkubtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dodajStavkubtnActionPerformed(evt);
            }
        });

        obrisiRacunbtn.setText("obrisi racun");
        obrisiRacunbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                obrisiRacunbtnActionPerformed(evt);
            }
        });

        jButton1.setText("kreiraj racun");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("sto");

        jButton2.setText("pretrazi po");

        jLabel2.setText("id");

        jLabel3.setText("roba");

        jLabel4.setText("sto");

        jLabel5.setText("zaposleni");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 134, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(prikaziStavkebtn, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dodajStavkubtn, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(obrisiRacunbtn, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jLabel1)
                        .addGap(38, 38, 38))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addContainerGap(212, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(prikaziStavkebtn)
                .addGap(18, 18, 18)
                .addComponent(dodajStavkubtn)
                .addGap(18, 18, 18)
                .addComponent(obrisiRacunbtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void prikaziStavkebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prikaziStavkebtnActionPerformed
        // TODO add your handling code here:
        int row = racuntab.getSelectedRow();
        if (row == -1) {
            frame.getMessagetxt().setText("Mora biti selektovan neki red");
            return;
        }
        StavkeRacunaPanel o=new StavkeRacunaPanel(modelRacun.getRacun(row));
        PanelFrame p=new PanelFrame(o);
        o.setFrame(p);
        frame.dispose();

    }//GEN-LAST:event_prikaziStavkebtnActionPerformed

    private void dodajStavkubtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dodajStavkubtnActionPerformed
        // TODO add your handling code here:
        int row = racuntab.getSelectedRow();
        if (row == -1) {
            frame.getMessagetxt().setText("Mora se odabrati neki racun");
            return;
        }
        NoviStavkaPanel p = new NoviStavkaPanel(modelRacun.getRacun(row));
        PanelFrame frame = new PanelFrame(p);
        p.setFrame(frame);
        this.frame.dispose();
    }//GEN-LAST:event_dodajStavkubtnActionPerformed

    private void obrisiRacunbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_obrisiRacunbtnActionPerformed
        // TODO add your handling code here:
        int row = racuntab.getSelectedRow();
        if (row == -1) {
            frame.getMessagetxt().setText("Mora biti selektovan neki racun iz tabele");
            return;
        }
        Racun r = modelRacun.getRacun(row);
        try {
            Racun info = ClientControler.getInstance().deleteRacun(r);
            frame.getMessagetxt().setText("Uspesno uklonjen racun s id " + info.getIdRacun());
            modelRacun = new RacunTableModel();
            racuntab.setModel(modelRacun);
        } catch (Exception ex) {
            frame.getMessagetxt().setText(ex.getMessage());
        }
    }//GEN-LAST:event_obrisiRacunbtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        LocalTime sad = LocalTime.now();
        double popust = 0;
        if (sad.isBefore(LocalTime.NOON)) {
            popust = 0.5;
        }

        //sto regulacija
        if (jComboBox1.getSelectedIndex() == -1) {
            frame.getMessagetxt().setText("Mora da se odabere neki sto");
        }
        Racun racun = new Racun(0, 0, sad, popust, 0, ClientControler.getInstance().getUlogovani(), (Sto) jComboBox1.getSelectedItem(), new ArrayList<>());
        try {
            Racun info = ClientControler.getInstance().noviRacun(racun);
            frame.getMessagetxt().setText("uspesno kreiran racun s id " + info.getIdRacun());
            modelRacun = new RacunTableModel();
            racuntab.setModel(modelRacun);
            this.repaint();
            this.revalidate();
        } catch (Exception ex) {
            frame.getMessagetxt().setText(ex.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton dodajStavkubtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<Sto> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JButton obrisiRacunbtn;
    private javax.swing.JButton prikaziStavkebtn;
    private javax.swing.JTable racuntab;
    // End of variables declaration//GEN-END:variables
}
