/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package front.panels.racunPaleni;

import controler.ClientControler;
import domain.Racun;
import domain.StavkaRacuna;
import front.panels.PanelFrame;
import front.tableModels.RacunTableModel;
import front.tableModels.StavkaRacunaTableModel;
import java.time.LocalTime;
import java.util.ArrayList;

/**
 *
 * @author jevrozim
 */
public class RacunPanel extends javax.swing.JPanel {

    private PanelFrame frame;
    private RacunTableModel modelRacun;
    private StavkaRacunaTableModel modelStavka;

    public void setFrame(PanelFrame frame) {
        this.frame = frame;
        try {
            modelRacun = new RacunTableModel();
            racuntab.setModel(modelRacun);
            this.setVisible(true);
        } catch (Exception ex) {
            frame.getMessagetxt().setText(ex.getMessage());
            deselectbtn.setEnabled(false);
            dodajStavkubtn.setEnabled(false);
            obrisiRacunbtn.setEnabled(false);
            prikaziStavkebtn.setEnabled(false);

        }
    }

    /**
     * Creates new form RacunPanel
     */
    public RacunPanel() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        racuntab = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        stavkaracunatab = new javax.swing.JTable();
        prikaziStavkebtn = new javax.swing.JButton();
        dodajStavkubtn = new javax.swing.JButton();
        obrisiRacunbtn = new javax.swing.JButton();
        deselectbtn = new javax.swing.JButton();
        izmenistavkubtn = new javax.swing.JButton();
        obrisistavkubtn = new javax.swing.JButton();

        racuntab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(racuntab);

        stavkaracunatab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(stavkaracunatab);

        prikaziStavkebtn.setText("prikazi stavke");
        prikaziStavkebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prikaziStavkebtnActionPerformed(evt);
            }
        });

        dodajStavkubtn.setText("dodaj stavku");
        dodajStavkubtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dodajStavkubtnActionPerformed(evt);
            }
        });

        obrisiRacunbtn.setText("obrisi racun");
        obrisiRacunbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                obrisiRacunbtnActionPerformed(evt);
            }
        });

        deselectbtn.setText("deselektuj racun");
        deselectbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deselectbtnActionPerformed(evt);
            }
        });

        izmenistavkubtn.setText("izmeni stavku");
        izmenistavkubtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                izmenistavkubtnActionPerformed(evt);
            }
        });

        obrisistavkubtn.setText("obrisi stavku");
        obrisistavkubtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                obrisistavkubtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(izmenistavkubtn, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(obrisistavkubtn, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 132, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(prikaziStavkebtn, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(dodajStavkubtn, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(obrisiRacunbtn, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(deselectbtn, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(135, 135, 135))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(prikaziStavkebtn)
                        .addGap(18, 18, 18)
                        .addComponent(dodajStavkubtn)
                        .addGap(18, 18, 18)
                        .addComponent(obrisiRacunbtn)
                        .addGap(18, 18, 18)
                        .addComponent(deselectbtn)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(izmenistavkubtn)
                        .addGap(18, 18, 18)
                        .addComponent(obrisistavkubtn)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void prikaziStavkebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prikaziStavkebtnActionPerformed
        // TODO add your handling code here:
        int row = racuntab.getSelectedRow();
        if (row == -1) {
            frame.getMessagetxt().setText("Mora biti selektovan neki red");
            return;
        }
        try {
            modelStavka = new StavkaRacunaTableModel(modelRacun.getRacun(row));
            stavkaracunatab.setModel(modelStavka);
            this.revalidate();
            this.repaint();
        } catch (Exception ex) {
            frame.getMessagetxt().setText(ex.getMessage());
            deselectbtn.setEnabled(false);
            dodajStavkubtn.setEnabled(false);
            obrisiRacunbtn.setEnabled(false);
            prikaziStavkebtn.setEnabled(false);
        }

    }//GEN-LAST:event_prikaziStavkebtnActionPerformed

    private void dodajStavkubtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dodajStavkubtnActionPerformed
        // TODO add your handling code here:
        int row = racuntab.getSelectedRow();
        if (row == -1) {
            frame.getMessagetxt().setText("Mora se odabrati neki racun");
            return;
        }
        NoviStavkaPanel p = new NoviStavkaPanel(modelRacun.getRacun(row));
        PanelFrame frame = new PanelFrame(p);
        p.setFrame(frame);
        this.frame.dispose();
    }//GEN-LAST:event_dodajStavkubtnActionPerformed

    private void deselectbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deselectbtnActionPerformed
        // TODO add your handling code here:
        try {
            StavkaRacunaTableModel model2 = new StavkaRacunaTableModel(new Racun(0, 0, null, 0, 0, null, null, new ArrayList<>()));
            stavkaracunatab.setModel(model2);
            this.repaint();
            this.revalidate();
        } catch (Exception e) {
            frame.getMessagetxt().setText(e.getMessage());
        }

    }//GEN-LAST:event_deselectbtnActionPerformed

    private void izmenistavkubtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_izmenistavkubtnActionPerformed
        // TODO add your handling code here:
        int row = stavkaracunatab.getSelectedRow();
        if (row == -1) {
            frame.getMessagetxt().setText("Mora biti selektovana neka stavka racuna");
            return;
        }
        UpdateStavkaPanel p = new UpdateStavkaPanel(modelStavka.getStavkaRacuna(row));
        PanelFrame f = new PanelFrame(p);
        p.setFrame(f);
        frame.dispose();
    }//GEN-LAST:event_izmenistavkubtnActionPerformed

    private void obrisistavkubtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_obrisistavkubtnActionPerformed
        // TODO add your handling code here:
        int row = stavkaracunatab.getSelectedRow();
        if (row == -1) {
            frame.getMessagetxt().setText("Mora nesto biti selektovano u tabeli stavke racuna");
            return;
        }
        StavkaRacuna stavka = modelStavka.getStavkaRacuna(row);
        int rowR = racuntab.getSelectedRow();
        if (rowR == -1) {
            frame.getMessagetxt().setText("Mora nesto biti selektovano u tabeli racuna");
            return;
        }
        Racun racun = modelRacun.getRacun(rowR);
        racun.getStavkeRacuna().remove(stavka);
        Racun info = ClientControler.getInstance().updateRacun(racun);
        frame.getMessagetxt().setText("uspesno uklonjena stavka racuna");
        try {
            modelStavka = new StavkaRacunaTableModel(info);
            stavkaracunatab.setModel(modelRacun);
        } catch (Exception e) {
            frame.getMessagetxt().setText(e.getMessage());

        }
        this.repaint();
        this.revalidate();
    }//GEN-LAST:event_obrisistavkubtnActionPerformed

    private void obrisiRacunbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_obrisiRacunbtnActionPerformed
        // TODO add your handling code here:
        int row = racuntab.getSelectedRow();
        if (row == -1) {
            frame.getMessagetxt().setText("Mora biti selektovan neki racun iz tabele");
            return;
        }
        Racun r = modelRacun.getRacun(row);
        try {
            Racun info = ClientControler.getInstance().deleteRacun(r);
            frame.getMessagetxt().setText("Uspesno uklonjen racun s id " + info.getIdRacun());
            modelRacun = new RacunTableModel();
            racuntab.setModel(modelRacun);
        } catch (Exception ex) {
            frame.getMessagetxt().setText(ex.getMessage());
        }
    }//GEN-LAST:event_obrisiRacunbtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deselectbtn;
    private javax.swing.JButton dodajStavkubtn;
    private javax.swing.JButton izmenistavkubtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton obrisiRacunbtn;
    private javax.swing.JButton obrisistavkubtn;
    private javax.swing.JButton prikaziStavkebtn;
    private javax.swing.JTable racuntab;
    private javax.swing.JTable stavkaracunatab;
    // End of variables declaration//GEN-END:variables
}
