/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package front;
import controler.ServerControler;
import java.awt.Color;
import threads.MainThread;
import dbb.DBB;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.IOException;


/**
 *
 * @author jevrozim
 */
public class ServerFrame extends javax.swing.JFrame {
    private MainThread mthread;

    /**
     * Creates new form ServerFrame
     */
    public ServerFrame() {
        initComponents();
        this.setVisible(true);
        connectedlabel.setForeground(Color.red);
        serverDiscbtn.setEnabled(false);
        
    }

    public static void main(String[] args) {
        ServerFrame frame=new ServerFrame();
        frame.setLocation(100, 200);
        Dimension screenSize=Toolkit.getDefaultToolkit().getScreenSize();
        int width=screenSize.width-frame.getWidth();
        frame.setLocation(width, 0);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        adresatxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        porttxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        bazatxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        ussernametxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        passwordtxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        connectbtn = new javax.swing.JButton();
        disconnectbtn = new javax.swing.JButton();
        connectedlabel = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        serverbtn = new javax.swing.JButton();
        serverAcctivitylbl = new javax.swing.JLabel();
        serverDiscbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Kredencijali");

        jLabel2.setText("adresa");

        adresatxt.setText("localhost");

        jLabel3.setText("port");

        porttxt.setText("3306");

        jLabel4.setText("ime baze podataka");

        bazatxt.setText("ps-projekat");

        jLabel5.setText("korisnicko ime");

        ussernametxt.setText("root");

        jLabel6.setText("sifra");

        jLabel7.setText("Konekcija");

        connectbtn.setText("Connect");
        connectbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connectbtnActionPerformed(evt);
            }
        });

        disconnectbtn.setText("Disconnect");
        disconnectbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disconnectbtnActionPerformed(evt);
            }
        });

        connectedlabel.setText("Disconnected");

        jLabel8.setText("Aktiviraj server");

        serverbtn.setText("ukljuci");
        serverbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serverbtnActionPerformed(evt);
            }
        });

        serverAcctivitylbl.setText("Server nije aktivan");

        serverDiscbtn.setText("iskljuci");
        serverDiscbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serverDiscbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(porttxt)
                                    .addComponent(bazatxt, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE))
                                .addGap(135, 135, 135)
                                .addComponent(connectedlabel)
                                .addGap(118, 118, 118))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(adresatxt, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                                    .addComponent(ussernametxt)
                                    .addComponent(passwordtxt))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(142, 142, 142)
                                        .addComponent(serverbtn)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(serverDiscbtn)
                                        .addContainerGap(32, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(connectbtn)
                                                .addGap(76, 76, 76)
                                                .addComponent(disconnectbtn)
                                                .addGap(20, 20, 20))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel8)
                                                .addGap(69, 69, 69))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(serverAcctivitylbl)
                                                .addGap(58, 58, 58))))))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addGap(130, 130, 130))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(adresatxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(connectbtn)
                            .addComponent(disconnectbtn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(porttxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(bazatxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(connectedlabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(ussernametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(passwordtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(serverbtn)
                    .addComponent(serverDiscbtn))
                .addGap(18, 18, 18)
                .addComponent(serverAcctivitylbl)
                .addContainerGap(184, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void connectbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connectbtnActionPerformed
        if(DBB.getInstance().connect(adresatxt.getText(), porttxt.getText(), bazatxt.getText(), ussernametxt.getText(), passwordtxt.getText())){
        connectedlabel.setText("Connected");
        connectedlabel.setForeground(Color.GREEN);    
        }
    }//GEN-LAST:event_connectbtnActionPerformed

    private void disconnectbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disconnectbtnActionPerformed
        if(DBB.getInstance().disconnect()){
        connectedlabel.setText("Disconnected");
        connectedlabel.setForeground(Color.red);    
        }
    }//GEN-LAST:event_disconnectbtnActionPerformed

    private void serverbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serverbtnActionPerformed
        // TODO add your handling code here:
        //pali i gasi server i njegovu nit
        mthread=new MainThread();

        mthread.start();
        serverbtn.setEnabled(false);
        serverDiscbtn.setEnabled(true);
        serverAcctivitylbl.setText("Server radi");
        serverAcctivitylbl.setForeground(Color.GREEN);
    }//GEN-LAST:event_serverbtnActionPerformed

    private void serverDiscbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serverDiscbtnActionPerformed
        try {
            // TODO add your handling code here:
            mthread.getServerSocket().close();
            serverAcctivitylbl.setText("Server ne radi");
            serverAcctivitylbl.setForeground(Color.RED);
            serverbtn.setEnabled(true);
            serverDiscbtn.setEnabled(false);
            
            ServerControler.getInstance().getUlogovani().clear();
            //OBAVEZNO OVO URADITI ISPOD HAUBE I NE DOZVOLITI KORISNIKU DA MOZE DA SE ZEZA SA OVIM STVARIMA
            //ILI KADA SE OVO DESI DA ODE SVIM KLIJENTIMA DA MORA DA SE UBIJU
            
        } catch (IOException ex) {
//            System.getLogger(ServerFrame.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            System.out.println("Problem pri zatvaranju konekcije "+ex.getMessage() );
        }
        
    }//GEN-LAST:event_serverDiscbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adresatxt;
    private javax.swing.JTextField bazatxt;
    private javax.swing.JButton connectbtn;
    private javax.swing.JLabel connectedlabel;
    private javax.swing.JButton disconnectbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField passwordtxt;
    private javax.swing.JTextField porttxt;
    private javax.swing.JLabel serverAcctivitylbl;
    private javax.swing.JButton serverDiscbtn;
    private javax.swing.JButton serverbtn;
    private javax.swing.JTextField ussernametxt;
    // End of variables declaration//GEN-END:variables
}
