/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package front.panels.zaposleniPaneli;

import controler.ClientControler;
import domain.Zaposleni;
import front.MainFrame;
import front.panels.PanelFrame;

/**
 *
 * @author jevrozim
 */
public class UpdateZaposleniPanel extends javax.swing.JPanel {

    private Zaposleni zaposleni;
    private PanelFrame frame;
    
    public UpdateZaposleniPanel(Zaposleni zaposleni) {
        this.zaposleni=zaposleni;
        initComponents();
        imetxt.setText(zaposleni.getIme());
        prezimetxt.setText(zaposleni.getPrezime());
        korisnickoImetxt.setText(zaposleni.getKorisnickoIme());
        sifratxt.setText(zaposleni.getSifra());
        this.setVisible(true);
    }
    public void setFrame(PanelFrame frame){
        this.frame=frame;
        frame.setTitle("Menjanje "+zaposleni);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        imetxt = new javax.swing.JTextField();
        prezimetxt = new javax.swing.JTextField();
        korisnickoImetxt = new javax.swing.JTextField();
        sifratxt = new javax.swing.JTextField();
        cancelbtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        updatebtn = new javax.swing.JButton();

        jLabel2.setText("prezime:");

        jLabel3.setText("korisnicko ime:");

        jLabel4.setText("sifra:");

        cancelbtn.setText("odustani");
        cancelbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelbtnActionPerformed(evt);
            }
        });

        jLabel1.setText("ime:");

        updatebtn.setText("izmeni");
        updatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(imetxt))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(prezimetxt))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(korisnickoImetxt))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sifratxt)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cancelbtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 157, Short.MAX_VALUE)
                                .addComponent(updatebtn)
                                .addGap(26, 26, 26)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(imetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(prezimetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(korisnickoImetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(sifratxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelbtn)
                    .addComponent(updatebtn))
                .addContainerGap(64, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cancelbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelbtnActionPerformed
        // TODO add your handling code here:
        MainFrame mainframe=new MainFrame();
        frame.dispose();
        
    }//GEN-LAST:event_cancelbtnActionPerformed

    private void updatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebtnActionPerformed
        // TODO add your handling code here:
        Zaposleni preporodjeni=new Zaposleni(zaposleni.getIdZaposleni(), imetxt.getText(), prezimetxt.getText(), korisnickoImetxt.getText(), sifratxt.getText());
        try {
            preporodjeni=ClientControler.getInstance().updateZaposleni(preporodjeni);
            //set sve da umre
            frame.getMessagetxt().setText("Promenjen je zaposleni " + preporodjeni);
                imetxt.setEditable(false);
                prezimetxt.setEditable(false);
                sifratxt.setEditable(false);
                korisnickoImetxt.setEditable(false);
                updatebtn.setEnabled(false);
                frame.getcacnelbtn().setText("Izadji");
        } catch (Exception ex) {
            frame.getMessagetxt().setText(ex.getMessage());
        }
    }//GEN-LAST:event_updatebtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelbtn;
    private javax.swing.JTextField imetxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField korisnickoImetxt;
    private javax.swing.JTextField prezimetxt;
    private javax.swing.JTextField sifratxt;
    private javax.swing.JButton updatebtn;
    // End of variables declaration//GEN-END:variables
}
