/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package front.panels.smenaPaneli;

import controler.ClientControler;
import domain.Smena;
import front.panels.PanelFrame;
import front.tableModels.SmenaTableModel;
import javax.swing.JOptionPane;

/**
 *
 * @author jevrozim
 */
public class SmenaPanel extends javax.swing.JPanel {

    /**
     * Creates new form SmenaPanel
     */
    
    private PanelFrame frame;
    private SmenaTableModel model;
    public SmenaPanel() {
        
    }
    public void setFrame(PanelFrame frame){
        this.frame=frame;
        try{
           model = new SmenaTableModel();
            initComponents();
            table.setModel(model);
        } catch (Exception e) {
            frame.getMessagetxt().setText(e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kreirajtbn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        obrisibtn = new javax.swing.JButton();
        izmenibtn = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        kreirajtbn.setText("Kreiraj");
        kreirajtbn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kreirajtbnActionPerformed(evt);
            }
        });

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table);

        obrisibtn.setText("Ukloni");
        obrisibtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                obrisibtnActionPerformed(evt);
            }
        });

        izmenibtn.setText("Izmeni");
        izmenibtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                izmenibtnActionPerformed(evt);
            }
        });

        jButton1.setText("pretrazi po");

        jLabel1.setText("id");

        jLabel2.setText("pocetak");

        jLabel3.setText("kraj");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(obrisibtn, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(izmenibtn, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(kreirajtbn, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(97, 97, 97))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(obrisibtn)
                        .addGap(18, 18, 18)
                        .addComponent(izmenibtn)
                        .addGap(18, 18, 18)
                        .addComponent(kreirajtbn)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addContainerGap(73, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void kreirajtbnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kreirajtbnActionPerformed
        // TODO add your handling code here:
        //privremeno resenje za novog zaposlenog
        NoviSmenaPanel p=new NoviSmenaPanel();
        PanelFrame frame = new PanelFrame(p);
        p.setFrame(frame);
        this.frame.dispose();//privremeno resenje takodje je moguce da samo na this frame zakacim
    }//GEN-LAST:event_kreirajtbnActionPerformed

    private void obrisibtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_obrisibtnActionPerformed
        // TODO add your handling code here:
        int row = table.getSelectedRow();
        if(row==-1){
            frame.getMessagetxt().setText("Nije oznacen ni jedan tip stola za ukloniti");
            return;
        }
        Smena pokojni = model.getSmena(row);
        int odgovor = JOptionPane.showConfirmDialog(frame, "Da li ste sigurni da zelite da uklonite " + pokojni, "", JOptionPane.YES_NO_OPTION);

        if (odgovor == JOptionPane.YES_OPTION) {
            try {
                Smena ts=ClientControler.getInstance().deleteSmena(pokojni);
                model = new SmenaTableModel();
                table.setModel(model);
                frame.getMessagetxt().setText("Uspesno uklonjen " + pokojni);
            } catch (Exception e) {
                frame.getMessagetxt().setText(e.getMessage());
            }
        }
    }//GEN-LAST:event_obrisibtnActionPerformed

    private void izmenibtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_izmenibtnActionPerformed
        // TODO add your handling code here:
        //izmeni stvari
        int row = table.getSelectedRow();
        if(row==-1){
            frame.getMessagetxt().setText("Nije odabran ni jedan zaposleni za izmeniti");
            return;
        }
        Smena izmenjeni = model.getSmena(row);
        //nesto nesto prikazi novi prozor koji menja zaposlenog
        UpdateSmenaPanel uf = new UpdateSmenaPanel(izmenjeni);
        PanelFrame noviFrame=new PanelFrame(uf);
        uf.setFrame(noviFrame);
        frame.dispose();//privremeno resenje moguce je samo na this frame da zakacim i rifresujem panel
    }//GEN-LAST:event_izmenibtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton izmenibtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JButton kreirajtbn;
    private javax.swing.JButton obrisibtn;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
