/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package front.panels.smenaPaneli;

import controler.ClientControler;
import domain.Smena;
import front.panels.PanelFrame;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;

/**
 *
 * @author jevrozim
 */
public class UpdateSmenaPanel extends javax.swing.JPanel {
    private PanelFrame frame;
    private Smena smena;
    /**
     * Creates new form UpdateSmenaPanel
     */
    public UpdateSmenaPanel(Smena smena) {
        this.smena=smena;
        initComponents();
        krajtxt.setText(smena.getKraj().toString());
        pocetaktxt.setText(smena.getPocetak().toString());
    }
    public void setFrame(PanelFrame frame){
        this.frame=frame;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pocetaktxt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        krajtxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        jButton1.setText("kreiraj");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("kraj");

        jLabel1.setText("pocetak");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pocetaktxt, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(krajtxt, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButton1)))
                        .addGap(8, 8, 8)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pocetaktxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(krajtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addComponent(jButton1)
                .addContainerGap(156, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("HH:mm");
        try{
            LocalTime pocetak=LocalTime.parse(pocetaktxt.getText(), formatter);
            LocalTime kraj=LocalTime.parse(krajtxt.getText(), formatter);
            if(kraj.isBefore(pocetak)){
                throw new Exception("Pocetak mora biti pre kraja");
            }
            Smena novi=new Smena(smena.getIdSmena(), pocetak, kraj);

            Smena info=ClientControler.getInstance().updateSmena(novi);
            frame.getMessagetxt().setText("uspesno izmenjena smena sa id "+info.getIdSmena());
            jButton1.setEnabled(false);
            pocetaktxt.setEditable(false);
            krajtxt.setEditable(false);
        }catch(DateTimeParseException e){
            frame.getMessagetxt().setText("Neispravno uneto vreme, mora biti formata HH:mm");
            return;
        }catch(Exception e){
            frame.getMessagetxt().setText(e.getMessage());
            return;
        }

    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField krajtxt;
    private javax.swing.JTextField pocetaktxt;
    // End of variables declaration//GEN-END:variables
}
